"""add shop inventory and stock movements

Revision ID: 6f34cce11c1a
Revises: e6930510b871
Create Date: 2026-08-13 11:28:02.977683

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime
import uuid


# revision identifiers, used by Alembic.
revision = '6f34cce11c1a'
down_revision = 'e6930510b871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_inventory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shop_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('stock_level', sa.Integer(), nullable=True),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_shop_inventory_product_id_products'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name='fk_shop_inventory_shop_id_shops'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'product_id', name='uq_shop_inventory_shop_product')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shop_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('stock_before', sa.Integer(), nullable=False),
    sa.Column('stock_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_stock_movements_created_by_users'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_stock_movements_product_id_products'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name='fk_stock_movements_shop_id_shops'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_shop_id'), ['shop_id'], unique=False)

    bind = op.get_bind()
    now = datetime.utcnow()
    shop_id = bind.execute(sa.text("select id from shops order by created_at limit 1")).scalar()
    if not shop_id:
        shop_id = str(uuid.uuid4())
        bind.execute(sa.text("""
            insert into shops (id, name, location, is_active, created_at, updated_at)
            values (:id, :name, :location, :is_active, :created_at, :updated_at)
        """), {
            'id': shop_id,
            'name': 'Main Shop',
            'location': '',
            'is_active': True,
            'created_at': now,
            'updated_at': now,
        })

    for table in ('users', 'shifts', 'transactions', 'expenses'):
        bind.execute(sa.text(f"update {table} set shop_id = :shop_id where shop_id is null"), {'shop_id': shop_id})

    owner_id = bind.execute(sa.text('select id from users where role = :role order by "createdAt" limit 1'), {'role': 'owner'}).scalar()
    products = bind.execute(sa.text("""
        select id, "stockLevel" as stock_level, "reorderLevel" as reorder_level
        from products
        where id not in (
            select product_id from shop_inventory where shop_id = :shop_id
        )
    """), {'shop_id': shop_id}).mappings().all()

    for product in products:
        stock_level = int(product['stock_level'] or 0)
        reorder_level = int(product['reorder_level'] or 10)
        bind.execute(sa.text("""
            insert into shop_inventory (id, shop_id, product_id, stock_level, reorder_level, updated_at)
            values (:id, :shop_id, :product_id, :stock_level, :reorder_level, :updated_at)
        """), {
            'id': str(uuid.uuid4()),
            'shop_id': shop_id,
            'product_id': product['id'],
            'stock_level': stock_level,
            'reorder_level': reorder_level,
            'updated_at': now,
        })
        bind.execute(sa.text("""
            insert into stock_movements (
                id, shop_id, product_id, type, quantity, stock_before, stock_after,
                reason, reference_type, reference_id, created_by, created_at
            )
            values (
                :id, :shop_id, :product_id, :type, :quantity, :stock_before, :stock_after,
                :reason, :reference_type, :reference_id, :created_by, :created_at
            )
        """), {
            'id': str(uuid.uuid4()),
            'shop_id': shop_id,
            'product_id': product['id'],
            'type': 'opening_balance',
            'quantity': stock_level,
            'stock_before': 0,
            'stock_after': stock_level,
            'reason': 'Migrated from product stock level',
            'reference_type': 'migration',
            'reference_id': revision,
            'created_by': owner_id,
            'created_at': now,
        })

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_shop_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_created_at'))

    op.drop_table('stock_movements')
    op.drop_table('shop_inventory')
    # ### end Alembic commands ###
