"""add shops

Revision ID: e6930510b871
Revises: fb43ff8816d2
Create Date: 2026-08-13 11:20:21.518330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6930510b871'
down_revision = 'fb43ff8816d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_expenses_shop_id_shops', 'shops', ['shop_id'], ['id'])

    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_shifts_shop_id_shops', 'shops', ['shop_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_transactions_shop_id_shops', 'shops', ['shop_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_users_shop_id_shops', 'shops', ['shop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_shop_id_shops', type_='foreignkey')
        batch_op.drop_column('shop_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_shop_id_shops', type_='foreignkey')
        batch_op.drop_column('shop_id')

    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_shifts_shop_id_shops', type_='foreignkey')
        batch_op.drop_column('shop_id')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_shop_id_shops', type_='foreignkey')
        batch_op.drop_column('shop_id')

    op.drop_table('shops')
    # ### end Alembic commands ###
